openapi: 3.0.0
info:
    title: My API
    version: 1.0.0
paths:
    /api/v1/users/signup:
        post:
            description: 새로운 사용자 생성
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                loginId:
                                    type: string
                                    description: 사용자 로그인 아이디
                                loginPw:
                                    type: string
                                    description: 사용자 로그인 비밀번호
                                name:
                                    type: string
                                    description: 사용자 이름
                                email:
                                    type: string
                                    description: 사용자 이메일
                                phone:
                                    type: string
                                    description: 사용자 전화번호
                                address:
                                    type: string
                                    description: 사용자 주소
                                extraAddr:
                                    type: string
                                    description: 사용자 상세주소 (선택)
                                birth:
                                    type: string
                                    description: 사용자 생년월일
                            required:
                                - loginId
                                - loginPw
                                - name
                                - email
                                - phone
                                - address
                                - birth
            responses:
                200:
                    description: 사용자 생성 성공
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: success
                400:
                    description: 사용자 생성 실패
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: request validation failed | email or loginId already exists
                                    code:
                                        type: string
                                        example: E000 | E001
    /api/v1/users/signin:
        post:
            description: 사용자 로그인
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                loginId:
                                    type: string
                                    description:: 사용자 로그인 아이디
                                loginPw:
                                    type: string
                                    description: 사용자 로그인 비밀번호
                            required:
                                - loginId
                                - loginPw
            responses:
                200:
                    description: 로그인 성공
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string
                                        example: jwt_token
                400:
                    description: 로그인 실패
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: request validation failed | user not found | password is incorrect
                                    code:
                                        type: string
                                        example: E000 | E002 | E003
